services:
  # finances:
  #   image: ${DOCKER_REGISTRY-}finances
  #   build:
  #     context: .
  #     dockerfile: FinancesApp_Api/Dockerfile
  #   ports:
  #     - "1410:8080"
  #   depends_on:
  #     - db
  #     - redis
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1470:1433"
    environment:
      SA_PASSWORD: "Numsey@Password!"
      ACCEPT_EULA: "Y"
  
  redis:
    image: redis:latest
    ports:
      - "1405:6379"
